apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapgameapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapgameapi
  template:
    metadata:
      labels:
        app: mapgameapi
    spec:
      containers:
      - name: mapgameapi
        image: vd84/golangapi:latest
        ports:
        - containerPort: 8010
---
apiVersion: v1
kind: Service
metadata:
  name: mapgameapi-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8010
  selector:
    app: mapgameapi